<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SkiaSharp" Version="4.151.0-rc.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\NodeVision.Rendering\NodeVision.Rendering.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Assets\" />
    </ItemGroup>

</Project>
